export const EMPLOYEES_DATA_LOADING = "EMPLOYEES_DATA_LOADING";
export const EMPLOYEES_DATA_SUCCESS = "EMPLOYEES_DATA_SUCCESS";
export const EMPLOYEES_DATA_FAILURE = "EMPLOYEES_DATA_FAILURE";

export const PATIENTS_DATA_LOADING = "PATIENTS_DATA_LOADING";
export const PATIENTS_DATA_SUCCESS = "PATIENTS_DATA_SUCCESS";
export const PATIENTS_DATA_FAILURE = "PATIENTS_DATA_FAILURE";


export const DELETE_DATA = "DELETE_DATA"